Repository with-dang/front, pull requests merged in 2024-08, with the labels that each got.

#2 Create issue templates
  .github/ISSUE_TEMPLATE/⚙chore-template.md
  .github/ISSUE_TEMPLATE/🎨-design-template.md
  .github/ISSUE_TEMPLATE/🔧fix-template.md
  .github/ISSUE_TEMPLATE/🛠-feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#4 Chore: 폴더 구조 세팅 & 페이지 라우팅 설정
  README.md
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/react.svg
  src/pages/index.tsx
  src/pages/login/index.tsx
  vite.config.ts
  yarn.lock
Labels: chore

#5 Design: 반응형 적용 & 메인 페이지 마감 임박 상품 1차 UI
  global.d.ts
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/assets/png/room.png
  src/assets/svg/mainLogo.svg
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/image/Image.tsx
  src/components/atoms/text/Text.tsx
  src/components/molecules/routerLabel/RouterLabel.tsx
  src/components/organisms/bottomSheet/BottomSheet.tsx
  src/components/organisms/header/Header.module.css
  src/components/organisms/header/Header.tsx
  src/components/organisms/nav/Nav.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/Soldout.tsx
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/main/soldout/SoldoutContent.tsx
  src/constants/images.ts
  src/index.css
  src/pages/_layout.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/styles/Color.ts
  src/types/home/index.ts
  src/types/home/type.ts
  svg.d.ts
  tsconfig.json
  vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: feat, design

#6 Design: mapChip
  index.html
  package-lock.json
  package.json
  src/assets/icons/Pill.tsx
  src/assets/icons/Scissors.tsx
  src/assets/icons/index.ts
  src/components/atoms/mapChip/MapChip.module.css
  src/components/atoms/mapChip/MapChip.tsx
  src/components/molecules/mapChipBox/MapChipBox.module.css
  src/components/molecules/mapChipBox/MapChipBox.tsx
  src/components/molecules/mapChipBox/constants.ts
Labels: feat, design

#7 Design: mapChip, MapChipBox
  index.html
  package-lock.json
  package.json
  src/assets/icons/Pill.tsx
  src/assets/icons/Scissors.tsx
  src/assets/icons/index.ts
  src/components/atoms/mapChip/MapChip.module.css
  src/components/atoms/mapChip/MapChip.tsx
  src/components/molecules/mapChipBox/MapChipBox.module.css
  src/components/molecules/mapChipBox/MapChipBox.tsx
  src/components/molecules/mapChipBox/constants.ts
Labels: feat, design

#8 Design: 마감 임박 상품 디자인 수정
  package-lock.json
  package.json
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/text/Text.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/SoldoutCard.tsx
  yarn.lock
Labels: design

#9 Design: 메인 페이지 마감 임박 상품 UI & 반응형, Atom 컴포넌트 생성
  global.d.ts
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/icons/Pill.tsx
  src/assets/icons/Scissors.tsx
  src/assets/icons/index.ts
  src/assets/png/room.png
  src/assets/svg/mainLogo.svg
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/image/Image.tsx
  src/components/atoms/mapChip/MapChip.module.css
  src/components/atoms/mapChip/MapChip.tsx
  src/components/atoms/text/Text.tsx
  src/components/molecules/mapChipBox/MapChipBox.module.css
  src/components/molecules/mapChipBox/MapChipBox.tsx
  src/components/molecules/mapChipBox/constants.ts
  src/components/molecules/routerLabel/RouterLabel.tsx
  src/components/organisms/bottomSheet/BottomSheet.tsx
  src/components/organisms/header/Header.module.css
  src/components/organisms/header/Header.tsx
  src/components/organisms/nav/Nav.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/Soldout.tsx
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/main/soldout/SoldoutContent.tsx
  src/constants/images.ts
  src/index.css
  src/pages/_layout.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/styles/Color.ts
  src/types/home/index.ts
  src/types/home/type.ts
  svg.d.ts
  tsconfig.json
  vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: feat, design

#10 Design: 지도 페이지 디자인
  src/assets/png/index.ts
  src/assets/png/mapCurrentLocation.png
  src/assets/png/mapIconAccommodation.png
  src/assets/png/mapIconBeauty.png
  src/assets/png/mapIconHospital.png
  src/assets/png/mapIconPill.png
  src/assets/png/mapIconRestaurant.png
  src/assets/png/mapIconShop.png
  src/components/atoms/mapChip/MapChip.module.css
  src/components/atoms/mapChip/MapChip.tsx
  src/components/molecules/mapChipBox/MapChipBox.module.css
  src/components/molecules/mapChipBox/MapChipBox.tsx
  src/components/molecules/mapChipBox/constants.ts
  src/components/views/map/components/CreateMap.css
  src/components/views/map/components/CreateMap.tsx
  src/components/views/map/components/mapCard/MapCard.module.css
  src/components/views/map/components/mapCard/MapCard.tsx
  src/components/views/map/components/mapCard/MapCardItem.tsx
  src/components/views/map/components/mapCard/MapCustomMarker.tsx
  src/components/views/map/constants/constant.ts
  src/pages/map/index.tsx
  src/pages/map/testConstant.ts
  src/types/map/index.ts
  src/types/map/type.ts
Labels: feat, design

#11 Feat: map 페이지 분리 및 헤더 컴포넌트 수정
  package-lock.json
  package.json
  src/assets/png/index.ts
  src/assets/png/logo.png
  src/assets/png/mainLogo.png
  src/components/molecules/mapChipBox/MapChipBox.module.css
  src/components/molecules/mapChipBox/MapChipBox.tsx
  src/components/molecules/routerLabel/RouterLabel.tsx
  src/components/organisms/header/Header.module.css
  src/components/organisms/header/Header.tsx
  src/components/views/map/MapPage.module.css
  src/components/views/map/MapPage.tsx
  src/components/views/map/components/CreateMap.module.css
  src/components/views/map/components/CreateMap.tsx
  src/hook/map/useSwipeHandler.ts
  src/pages/map/index.tsx
  src/styles/Color.ts
Labels: feat, design

#12 Design: mypage 디자인
  src/assets/png/Receipt.png
  src/components/views/mypage/Mypage.module.css
  src/components/views/mypage/Mypage.tsx
  src/components/views/mypage/constants.ts
  src/pages/mypage/index.tsx
Labels: feat, design

#13 Design: 결제 내역 조회 및 상세보기 페이지 디자인
  src/assets/png/dogIcon.png
  src/assets/png/index.ts
  src/assets/png/personIcon.png
  src/components/molecules/priceBox/PriceBox.tsx
  src/components/molecules/priceBox/PriveBox.module.css
  src/components/views/paymentHistory/PaymentHistoryDetail.tsx
  src/components/views/paymentHistory/PaymentHistoy.module.css
  src/components/views/paymentHistory/PaymentHistoy.tsx
  src/components/views/paymentHistory/PaymentHistoyDetail.module.css
  src/components/views/paymentHistory/components/PaymentHistoryCard.module.css
  src/components/views/paymentHistory/components/PaymentHistoryCard.tsx
  src/components/views/paymentHistory/components/PaymentHistoryDetailPersonnel.module.css
  src/components/views/paymentHistory/components/PaymentHistoryDetailPersonnel.tsx
  src/components/views/paymentHistory/components/PaymentHistoryPriceBox.module.css
  src/components/views/paymentHistory/components/PaymentHistoryPriceBox.tsx
  src/components/views/paymentHistory/constants/constant.ts
  src/pages/payment-history/detail/index.tsx
  src/pages/payment-history/index.tsx
  src/utils/formatNumber.ts
Labels: feat, design

#14 Design: 공동구매 페이지 UI
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/atoms/check/Check.module.css
  src/components/atoms/check/Check.tsx
  src/components/atoms/chip/Chip.module.css
  src/components/atoms/chip/Chip.tsx
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/image/Image.tsx
  src/components/molecules/chipBox/ChipBox.tsx
  src/components/molecules/chipBox/const.ts
  src/components/molecules/progress/Progress.module.css
  src/components/molecules/progress/Progress.tsx
  src/components/molecules/routerLabel/RouterLabel.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/slider/SampleSlider.tsx
  src/components/views/main/adverSlider/AdverSlider.tsx
  src/components/views/main/pick/Pick.module.css
  src/components/views/main/pick/Pick.tsx
  src/components/views/main/pick/PickContent.tsx
  src/components/views/main/pick/PickImg.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/Soldout.tsx
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/purchase/Purchase.module.css
  src/components/views/purchase/PurchaseCard.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/components/views/purchase/PurchaseHeader.tsx
  src/components/views/purchase/Search.tsx
  src/pages/index.tsx
  src/pages/purchase/index.tsx
  src/styles/Color.ts
  yarn.lock
Labels: feat

#16 Design: 공동구매 상세 페이지 UI
  src/App.tsx
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/image/Image.tsx
  src/components/organisms/header/Header.tsx
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutContent.tsx
  src/components/views/purchase/Purchase.module.css
  src/components/views/purchase/PurchaseCard.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/components/views/purchase/detail/PurDetail.const.ts
  src/components/views/purchase/detail/PurDetail.module.css
  src/components/views/purchase/detail/PurDetail.tsx
  src/components/views/purchase/detail/PurDetailInfo.tsx
  src/components/views/purchase/detail/PurDetailMain.tsx
  src/components/views/purchase/detail/PurDetailMap.tsx
  src/pages/purchase/[id]/index.tsx
  src/pages/purchase/index.tsx
  src/types/home/type.ts
Labels: fix, design

#17 Design: payment 페이지 UI
  src/components/atoms/button/Button.tsx
  src/components/atoms/stepper/Stepper.module.css
  src/components/atoms/stepper/Stepper.tsx
  src/components/views/payment/Payment.module.css
  src/components/views/payment/Payment.tsx
  src/components/views/payment/PaymentInfo.tsx
  src/components/views/payment/PaymentInfoCount.tsx
  src/components/views/payment/PaymentMethod.tsx
  src/components/views/payment/PaymentPrice.tsx
  src/pages/payment/index.tsx
Labels: feat, design

#18 Design: 공동구매 상세 페이지 UI & payment 페이지 UI
  src/App.tsx
  src/components/atoms/button/Button.tsx
  src/components/atoms/iconLabel/IconLabel.tsx
  src/components/atoms/image/Image.tsx
  src/components/atoms/stepper/Stepper.module.css
  src/components/atoms/stepper/Stepper.tsx
  src/components/organisms/header/Header.tsx
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutContent.tsx
  src/components/views/payment/Payment.module.css
  src/components/views/payment/Payment.tsx
  src/components/views/payment/PaymentInfo.tsx
  src/components/views/payment/PaymentInfoCount.tsx
  src/components/views/payment/PaymentMethod.tsx
  src/components/views/payment/PaymentPrice.tsx
  src/components/views/purchase/Purchase.module.css
  src/components/views/purchase/PurchaseCard.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/components/views/purchase/detail/PurDetail.const.ts
  src/components/views/purchase/detail/PurDetail.module.css
  src/components/views/purchase/detail/PurDetail.tsx
  src/components/views/purchase/detail/PurDetailInfo.tsx
  src/components/views/purchase/detail/PurDetailMain.tsx
  src/components/views/purchase/detail/PurDetailMap.tsx
  src/pages/payment/index.tsx
  src/pages/purchase/[id]/index.tsx
  src/pages/purchase/index.tsx
  src/types/home/type.ts
Labels: feat, design

#19 Feat: 마이페이지 디자인 및 여행지 픽 페이지 디자인
  src/components/views/mypage/Mypage.module.css
  src/components/views/mypage/Mypage.tsx
  src/components/views/pick/Pick.module.css
  src/components/views/pick/PickDetail.tsx
  src/components/views/pick/PickItem.tsx
  src/components/views/pick/PickList.tsx
  src/pages/mypage/index.tsx
  src/pages/payment-history/detail/index.tsx
  src/pages/pick/detail/index.tsx
  src/pages/pick/index.tsx
Labels: feat, design
