Repository with-dang/front, pull requests merged in 2024-10, with the labels that each got.

#21 feat: 여행지 pick 리스트, 상세보기 api연결
  package-lock.json
  src/components/views/main/pick/Pick.tsx
  src/components/views/main/pick/PickContent.tsx
  src/components/views/main/pick/PickImg.tsx
  src/components/views/pick/PickDetail.tsx
  src/components/views/pick/PickItem.tsx
  src/components/views/pick/PickList.tsx
  src/hook/commonApi.ts
  src/hook/pick/usePickItemDetailQuery.ts
  src/hook/pick/usePickItemListQuery.ts
  src/types/map/type.ts
  yarn.lock
Labels: feat

#22 Feat: toss 결제 연동 완료
  .env
  src/components/views/payment/PaymentLoading.tsx
  src/components/views/payment/PaymentMethod.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/hook/commonApi.ts
  src/hook/payment/useRequestPayment.ts
  src/hook/payment/useSuccessPayment.ts
  src/pages/payment/loading/index.tsx
  src/types/home/type.ts
Labels: feat

#23 Feat: 공구 목록 & 상세 & 구매 페이지 api 연동
  src/components/UI/atoms/stepper/Stepper.tsx
  src/components/UI/organisms/bottomSheet/BottomSheet.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/main/soldout/SoldoutContent.tsx
  src/components/views/payment/Payment.tsx
  src/components/views/payment/PaymentInfo.tsx
  src/components/views/payment/PaymentInfoCount.tsx
  src/components/views/payment/PaymentPrice.tsx
  src/components/views/purchase/PurchaseCard.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/components/views/purchase/detail/PurDetail.module.css
  src/components/views/purchase/detail/PurDetail.tsx
  src/components/views/purchase/detail/PurDetailMain.tsx
  src/hook/purchase/usePurchaseDetailQuery.ts
  src/pages/payment/[id]/index.tsx
  src/types/home/type.ts
  src/types/purchase/type.ts
  src/utils/formatDate.ts
  src/utils/formatPrice.ts
Labels: fix, feat

#24 Feat: Nav 생성, 지도 연결
  src/components/UI/organisms/nav/Nav.module.css
  src/components/UI/organisms/nav/Nav.tsx
  src/components/UI/organisms/nav/constant.ts
  src/components/views/map/MapPage.tsx
  src/components/views/map/components/CreateMap.tsx
  src/components/views/map/components/mapCard/MapCustomMarker.tsx
  src/components/views/mypage/Mypage.tsx
  src/hook/commonApi.ts
  src/hook/map/useMapItemListQuery.ts
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/payment-history/index.tsx
  src/pages/pick/detail/index.tsx
  src/pages/pick/index.tsx
  src/pages/purchase/index.tsx
  src/types/map/type.ts
  src/types/paymentHistory/index.ts
  src/types/paymentHistory/type.ts
Labels: feat

#28 Feat/dev : nav 위치 변경
  src/App.css
  src/App.tsx
  src/components/UI/organisms/nav/Nav.module.css
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/mypage/Mypage.tsx
  src/components/views/paymentHistory/PaymentHistoy.tsx
  src/components/views/paymentHistory/components/PaymentHistoryCard.tsx
  src/hook/history/usePaymentHistoryQuery.ts
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/payment-history/index.tsx
  src/pages/pick/detail/index.tsx
  src/pages/pick/index.tsx
  src/pages/purchase/index.tsx
  src/types/paymentHistory/type.ts
  src/utils/formatDate.ts
Labels: feat

#30 Feat: 공동구매 counter 구현 & Nav 디자인 수정
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/assets/png/home.png
  src/assets/png/off_map.png
  src/assets/png/off_payment.png
  src/assets/png/off_profile.png
  src/assets/png/off_purchase.png
  src/assets/png/on_map.png
  src/assets/png/on_payment.png
  src/assets/png/on_profile.png
  src/assets/png/on_purchase.png
  src/components/UI/organisms/nav/Nav.module.css
  src/components/UI/organisms/nav/Nav.tsx
  src/components/UI/organisms/nav/constant.ts
  src/components/views/main/pick/PickContent.tsx
  src/components/views/main/soldout/Soldout.module.css
  src/components/views/main/soldout/SoldoutCard.tsx
  src/components/views/main/soldout/SoldoutCardImg.tsx
  src/components/views/payment/PaymentLoading.tsx
  src/components/views/payment/PaymentMethod.tsx
  src/components/views/purchase/PurchaseCard.tsx
  src/components/views/purchase/PurchaseContent.tsx
  src/components/views/purchase/PurchaseHeader.tsx
  src/components/views/purchase/Search.tsx
  src/components/views/purchase/detail/PurDetail.tsx
  src/components/views/purchase/detail/PurDetailInfo.tsx
  src/hook/commonApi.ts
  src/hook/login/useLoginMutation.ts
  src/pages/index.tsx
  src/pages/purchase/index.tsx
  src/types/purchase/type.ts
  src/utils/formatDate.ts
  vite.config.ts
  yarn.lock
Labels: feat, design

#37 Update .env
  .env
  src/hook/commonApi.ts
Labels: fix
